### PR TITLE
[iOS] Fix: Converting from WebP causes app crash

### PR DESCRIPTION
**Pull request by novikov-studio**
Unable converting from WebP to anything under iOS.

From [UIImage](https://developer.apple.com/documentation/uikit/uiimage) docs: 
`image objects support all platform-native image formats`

From [WebP type property](https://developer.apple.com/documentation/uniformtypeidentifiers/uttype/3551599-webp) docs:
`Available on iOS 14.0 and later`

This PR uses SDWebImage to load source WebP image.

### CODE REVIEW

**Comment by novikov-studio** [comment]
Done.

**Comment by AlexV525** [comment]
Great. Just wondering, is WebPs available for compress on Android at present (I'm not closely maintaining the plugin)?

**Comment by novikov-studio** [comment]
From my experience, webp-to-jpeg (with this plugin) works well on Android.

**Comment by AlexV525** [comment]
Sorry for the late feedback. Thanks again. Merging.

**Pull request merged**
