### PR TITLE
update Kotlin version and compile options

### LINKED ISSUE #270: [Discussions] does plan support android jdk 17
### Content

_No response_

### PR DESCRIPTION
**Pull request by VictorUvarov**
Fixes #270

### CODE REVIEW

**Comment by ynmain** [comment]
Hello.

we are in trouble.
I hope this is merged and released soon.

Any app that uses stripe will fail to build.
Stripe has migrated Gradle version to 8.x, and many people are having a hard time due to low compileSdkVersion of flutter_image_compress.

**Comment by IdemenB** [comment]
Is there a way to use this before it is merged?

**Comment by saputross** [comment]
still waiting to this update. hope this to be release soon.

**Comment by DDavidPrime** [comment]
@CaiJingLong 
Can we have this merged and published? A lot of people are depending on this fix.

**Pull request closed without merging**
